name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  PYTHON_VERSION: '3.10'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          go-version: ${{ env.PYTHON_VERSION }}

      - name: Run Unit Tests
        run: python3 -m unittest
